<a href="https://colab.research.google.com/github/MiniomTarolero/Actividad-1-Extracci-n-de-datos-/blob/main/CountryTable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Importamos librerias requeridas
import io
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

Saving CountryTable.csv to CountryTable.csv

{'CountryTable.csv': b'code,name,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2\r\nABW,Aruba,North America,Caribbean,193,,103000,78.4,828,793,Aruba,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,129,AW\r\nAFG,Afghanistan,Asia,Southern and Central Asia,652090,1919,22720000,45.9,5976,,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1,AF\r\nAGO,Angola,Africa,Central Africa,1246700,1975,12878000,38.3,6648,7984,Angola,Republic,Jose Eduardo dos Santos,56,AO\r\nAIA,Anguilla,North America,Caribbean,96,,8000,76.1,63.2,,Anguilla,Dependent Territory of the uK,Elisabeth II,62,AI\r\nALB,Albania,Europe,Southern Europe,28748,1912,3401200,71.6,3205,2500,Shqiperia,Republic,Rexhep Mejdani,34,AL\r\nAND,Andorra,Europe,Southern Europe,468,1278,78000,83.5,1630,,Andorra,Parliamentary Coprincipality,,55,AD\r\nANT,Netherlands Antilles,North America,Caribbean,800,,217000,74.7,1941,,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,33,AN\r\nARE,united Arab Emirates,Asia,Middle East,83600,1971,2441000,74.1,37966,36846,Al-Imarat al- Arabiya al-Muttahida,Emirate Federation,Zayid bin Sultan al-Nahayan,65,AE\r\nARG,Argentina,South America,South America,2780400,1816,37032000,75.1,340238,323310,Argentina,Federal Republic,Fernando de la Rua,69,AR\r\nARM,Armenia,Asia,Middle East,29800,1991,3520000,66.4,1813,1627,Hajastan,Republic,Robert KotSarjan,126,AM\r\nASM,American Samoa,Oceania,Polynesia,199,,68000,75.1,334,,Amerika Samoa,uS Territory,George W. Bush,54,AS\r\nATA,Antarctica,Antarctica,Antarctica,13120000,,0,,0,,N/A,Co-administrated,,,AQ\r\nATF,French Southern territories,Antarctica,Antarctica,7780,,0,,0,,Terres australes francaises,Nonmetropolitan Territory of France,Jacques Chirac,,TF\r\nATG,Antigua and Barbuda,North America,Caribbean,442,1981,68000,70.5,612,584,Antigua and Barbuda,Constitutional Monarchy,Elisabeth II,63,AG\r\nAuS,Australia,Oceania,Australia and New Zealand,7741220,1901,18886000,79.8,351182,392911,Australia,"Constitutional Monarchy, Federation",Elisabeth II,135,Au\r\nAuT,Austria,Europe,Western Europe,83859,1918,8091800,77.7,211860,206025,osterreich,Federal Republic,Thomas Klestil,1523,AT\r\nAZE,Azerbaijan,Asia,Middle East,86600,1991,7734000,62.9,4127,4100,Azarbaycan,Federal Republic,Heydar aliyev,144,AZ\r\nBDI,Burundi,Africa,Eastern Africa,27834,1962,6695000,46.2,903,982,Burundi/uburundi,Republic,Pierre Buyoya,552,BI\r\nBEL,Belgium,Europe,Western Europe,30518,1830,10239000,77.8,249704,243948,Belgie/Belgique,"Constitutional Monarchy, Federation",Albert II,179,BE\r\nBEN,Benin,Africa,Western Africa,112622,1960,6097000,50.2,2357,2141,Benin,Republic,Mathieu Kerekou,187,BJ\r\nBFA,Burkina Faso,Africa,Western Africa,274000,1960,11937000,46.7,2425,2201,Burkina Faso,Republic,Blaise Compaore,549,BF\r\nBGD,Bangladesh,Asia,Southern and Central Asia,143998,1971,129155000,60.2,32852,31966,Bangladesh,Republic,Shahabuddin Ahmad,150,BD\r\nBGR,Bulgaria,Europe,Eastern Europe,110994,1908,8190900,70.9,12178,10169,Balgarija,Republic,Petar Stojanov,539,BG\r\nBHR,Bahrain,Asia,Middle East,694,1971,617000,73,6366,6097,Al-Bahrayn,Monarchy (Emirate),Hamad ibn Isa al-Khalifa,149,BH\r\nBHS,Bahamas,North America,Caribbean,13878,1973,307000,71.1,3527,3347,The Bahamas,Constitutional Monarchy,Elisabeth II,148,BS\r\nBIH,Bosnia and Herzegovina,Europe,Southern Europe,51197,1992,3972000,71.5,2841,,Bosna i Hercegovina,Federal Republic,Ante Jelavic,201,BA\r\nBLR,Belarus,Europe,Eastern Europe,207600,1991,10236000,68,13714,,Belarus,Republic,Aljaksandr LukaSenka,3520,BY\r\nBLZ,Belize,North America,Central America,22696,1981,241000,70.9,630,616,Belize,Constitutional Monarchy,Elisabeth II,185,BZ\r\nBMu,Bermuda,North America,North America,53,,65000,76.9,2328,2190,Bermuda,Dependent Territory of the uK,Elisabeth II,191,BM\r\nBOL,Bolivia,South America,South America,1098581,1825,8329000,63.7,8571,7967,Bolivia,Republic,Hugo Banzer Suarez,194,BO\r\nBRA,Brazil,South America,South America,8547403,1822,170115000,62.9,776739,804108,Brasil,Federal Republic,Fernando Henrique Cardoso,211,BR\r\nBRB,Barbados,North America,Caribbean,430,1966,270000,73,2223,2186,Barbados,Constitutional Monarchy,Elisabeth II,174,BB\r\nBRN,Brunei,Asia,Southeast Asia,5765,1984,328000,73.6,11705,12460,Brunei Darussalam,Monarchy (Sultanate),Haji Hassan al-Bolkiah,538,BN\r\nBTN,Bhutan,Asia,Southern and Central Asia,47000,1910,2124000,52.4,372,383,Druk-Yul,Monarchy,Jigme Singye Wangchuk,192,BT\r\nBVT,Bouvet Island,Antarctica,Antarctica,59,,0,,0,,Bouvetoya,Dependent Territory of Norway,Harald V,,BV\r\nBWA,Botswana,Africa,Southern Africa,581730,1966,1622000,39.3,4834,4935,Botswana,Republic,Festus G. Mogae,204,BW\r\nCAF,Central African Republic,Africa,Central Africa,622984,1960,3615000,44,1054,993,Centrafrique/Be-Afrika,Republic,Ange-Felix Patasse,1889,CF\r\nCAN,Canada,North America,North America,9970610,1867,31147000,79.4,598862,625626,Canada,"Constitutional Monarchy, Federation",Elisabeth II,1822,CA\r\nCCK,Cocos (Keeling) Islands,Oceania,Australia and New Zealand,14,,600,,0,,Cocos (Keeling) Islands,Territory of Australia,Elisabeth II,2317,CC\r\nCHE,Switzerland,Europe,Western Europe,41284,1499,7160400,79.6,264478,256092,Schweiz/Suisse/Svizzera/Svizra,Federation,Adolf Ogi,3248,CH\r\nCHL,Chile,South America,South America,756626,1810,15211000,75.7,72949,75780,Chile,Republic,Ricardo Lagos Escobar,554,CL\r\nCHN,China,Asia,Eastern Asia,9572900,-1523,1277558000,71.4,982268,917719,Zhongquo,People\'sRepublic,Jiang Zemin,1891,CN\r\nCIV,Cote dIvoire,Africa,Western Africa,322463,1960,14786000,45.2,11345,10285,Cote dIvoire,Republic,Laurent Gbagbo,2814,CI\r\nCMR,Cameroon,Africa,Central Africa,475442,1960,15085000,54.8,9174,8596,Cameroun/Cameroon,Republic,Paul Biya,1804,CM\r\nCOD,"Congo, The Democratic Republic of the",Africa,Central Africa,2344858,1960,51654000,48.8,6964,2474,Republique Democratique du Congo,Republic,Joseph Kabila,2298,CD\r\nCOG,Congo,Africa,Central Africa,342000,1960,2943000,47.4,2108,2287,Congo,Republic,Denis Sassou-Nguesso,2296,CG\r\nCOK,Cook Islands,Oceania,Polynesia,236,,20000,71.1,100,,The Cook Islands,Nonmetropolitan Territory of New Zealand,Elisabeth II,583,CK\r\nCOL,Colombia,South America,South America,1138914,1810,42321000,70.3,102896,105116,Colombia,Republic,Andres Pastrana Arango,2257,CO\r\nCOM,Comoros,Africa,Eastern Africa,1862,1975,578000,60,4401,4361,Komori/Comores,Republic,Azali Assoumani,2295,KM\r\nCPV,Cape Verde,Africa,Western Africa,4033,1975,428000,68.9,435,420,Cabo Verde,Republic,Antonio Mascarenhas Monteiro,1859,CV\r\nCRI,Costa Rica,North America,Central America,51100,1821,4023000,75.8,10226,9757,Costa Rica,Republic,Miguel angel RodrIguez EcheverrIa,584,CR\r\nCuB,Cuba,North America,Caribbean,110861,1902,11201000,76.2,17843,18862,Cuba,Socialistic Republic,Fidel Castro Ruz,2413,Cu\r\nCXR,Christmas Island,Oceania,Australia and New Zealand,135,,2500,,0,,Christmas Island,Territory of Australia,Elisabeth II,1791,CX\r\nCYM,Cayman Islands,North America,Caribbean,264,,38000,78.9,1263,1186,Cayman Islands,Dependent Territory of the uK,Elisabeth II,553,KY\r\nCYP,Cyprus,Asia,Middle East,9251,1960,754700,76.7,9333,8246,Kypros/Kibris,Republic,Glafkos Klerides,2430,CY\r\nCZE,Czech Republic,Europe,Eastern Europe,78866,1993,10278100,74.5,55017,52037,esko,Republic,Vaclav Havel,3339,CZ\r\nDEu,Germany,Europe,Western Europe,357022,1955,82164700,77.4,2133367,2102826,Deutschland,Federal Republic,Johannes Rau,3068,DE\r\nDJI,Djibouti,Africa,Eastern Africa,23200,1977,638000,50.8,382,373,Djibouti/Jibuti,Republic,Ismail Omar Guelleh,585,DJ\r\nDMA,Dominica,North America,Caribbean,751,1978,71000,73.4,256,243,Dominica,Republic,Vernon Shaw,586,DM\r\nDNK,Denmark,Europe,Nordic Countries,43094,800,5330000,76.5,174099,169264,Danmark,Constitutional Monarchy,Margrethe II,3315,DK\r\nDOM,Dominican Republic,North America,Caribbean,48511,1844,8495000,73.2,15846,15076,Republica Dominicana,Republic,Hipolito MejIa DomInguez,587,DO\r\nDZA,Algeria,Africa,Northern Africa,2381741,1962,31471000,69.7,49982,46966,Al-Jazair/Algerie,Republic,Abdelaziz Bouteflika,35,DZ\r\nECu,Ecuador,South America,South America,283561,1822,12646000,71.1,19770,19769,Ecuador,Republic,Gustavo Noboa Bejarano,594,EC\r\nEGY,Egypt,Africa,Northern Africa,1001449,1922,68470000,63.3,82710,75617,Misr,Republic,Hosni Mubarak,608,EG\r\nERI,Eritrea,Africa,Eastern Africa,117600,1993,3850000,55.8,650,755,Ertra,Republic,Isayas Afewerki [Isaias Afwerki],652,ER\r\nESH,Western Sahara,Africa,Northern Africa,266000,,293000,49.8,60,,As-Sahrawiya,Occupied by Marocco,Mohammed Abdel Aziz,2453,EH\r\nESP,Spain,Europe,Southern Europe,505992,1492,39441700,78.8,553233,532031,Espana,Constitutional Monarchy,Juan Carlos I,653,ES\r\nEST,Estonia,Europe,Baltic Countries,45227,1991,1439200,69.5,5328,3371,Eesti,Republic,Lennart Meri,3791,EE\r\nETH,Ethiopia,Africa,Eastern Africa,1104300,-1000,62565000,45.2,6353,6180,YeItyop iya,Republic,Negasso Gidada,756,ET\r\nFIN,Finland,Europe,Nordic Countries,338145,1917,5171300,77.4,121914,119833,Suomi,Republic,Tarja Halonen,3236,FI\r\nFJI,Fiji Islands,Oceania,Melanesia,18274,1970,817000,67.9,1536,2149,Fiji Islands,Republic,Josefa Iloilo,764,FJ\r\nFLK,Falkland Islands,South America,South America,12173,,2000,,0,,Falkland Islands,Dependent Territory of the uK,Elisabeth II,763,FK\r\nFRA,France,Europe,Western Europe,551500,843,59225700,78.8,1424285,1392448,France,Republic,Jacques Chirac,2974,FR\r\nFRO,Faroe Islands,Europe,Nordic Countries,1399,,43000,78.4,0,,Foroyar,Part of Denmark,Margrethe II,901,FO\r\nFSM,"Micronesia, Federated States of",Oceania,Micronesia,702,1990,119000,68.6,212,,Micronesia,Federal Republic,Leo A. Falcam,2689,FM\r\nGAB,Gabon,Africa,Central Africa,267668,1960,1226000,50.1,5493,5279,Le Gabon,Republic,Omar Bongo,902,GA\r\nGBR,united Kingdom,Europe,British Islands,242900,1066,59623400,77.7,1378330,1296830,united Kingdom,Constitutional Monarchy,Elisabeth II,456,GB\r\nGEO,Georgia,Asia,Middle East,69700,1991,4968000,64.5,6064,5924,Sakartvelo,Republic,Eduard Sevardnadze,905,GE\r\nGHA,Ghana,Africa,Western Africa,238533,1957,20212000,57.4,7137,6884,Ghana,Republic,John Kufuor,910,GH\r\nGIB,Gibraltar,Europe,Southern Europe,6,,25000,79,258,,Gibraltar,Dependent Territory of the uK,Elisabeth II,915,GI\r\nGIN,Guinea,Africa,Western Africa,245857,1958,7430000,45.6,2352,2383,Guinee,Republic,Lansana Conte,926,GN\r\nGLP,Guadeloupe,North America,Caribbean,1705,,456000,77,3501,,Guadeloupe,Overseas Department of France,Jacques Chirac,919,GP\r\nGMB,Gambia,Africa,Western Africa,11295,1965,1305000,53.2,320,325,The Gambia,Republic,Yahya Jammeh,904,GM\r\nGNB,Guinea-Bissau,Africa,Western Africa,36125,1974,1213000,49,293,272,Guine-Bissau,Republic,Kumba Iala,927,GW\r\nGNQ,Equatorial Guinea,Africa,Central Africa,28051,1968,453000,53.6,283,542,Guinea Ecuatorial,Republic,Teodoro Obiang Nguema Mbasogo,2972,GQ\r\nGRC,Greece,Europe,Southern Europe,131626,1830,10545700,78.4,120724,119946,Ellada,Republic,Kostis Stefanopoulos,2401,GR\r\nGRD,Grenada,North America,Caribbean,344,1974,94000,64.5,318,,Grenada,Constitutional Monarchy,Elisabeth II,916,GD\r\nGRL,Greenland,North America,North America,2166090,,56000,68.1,0,,Kalaallit Nunaat/Gronland,Part of Denmark,Margrethe II,917,GL\r\nGTM,Guatemala,North America,Central America,108889,1821,11385000,66.2,19008,17797,Guatemala,Republic,Alfonso Portillo Cabrera,922,GT\r\nGuF,French Guiana,South America,South America,90000,,181000,76.1,681,,Guyane francaise,Overseas Department of France,Jacques Chirac,3014,GF\r\nGuM,Guam,Oceania,Micronesia,549,,168000,77.8,1197,1136,Guam,uS Territory,George W. Bush,921,Gu\r\nGuY,Guyana,South America,South America,214969,1966,861000,64,722,743,Guyana,Republic,Bharrat Jagdeo,928,GY\r\nHKG,Hong Kong,Asia,Eastern Asia,1075,,6782000,79.5,166448,173610,Xianggang/Hong Kong,Special Administrative Region of China,Jiang Zemin,937,HK\r\nHMD,Heard Island and McDonald Islands,Antarctica,Antarctica,359,,0,,0,,Heard and McDonald Islands,Territory of Australia,Elisabeth II,,HM\r\nHND,Honduras,North America,Central America,112088,1838,6485000,69.9,5333,4697,Honduras,Republic,Carlos Roberto Flores Facusse,933,HN\r\nHRV,Croatia,Europe,Southern Europe,56538,1991,4473000,73.7,20208,19300,Hrvatska,Republic,Stipe Mesic,2409,HR\r\nHTI,Haiti,North America,Caribbean,27750,1804,8222000,49.2,3459,3107,Haiti/Dayti,Republic,Jean-Bertrand Aristide,929,HT\r\nHuN,Hungary,Europe,Eastern Europe,93030,1918,10043200,71.4,48267,45914,Magyarorszag,Republic,Ferenc Madl,3483,Hu\r\nIDN,Indonesia,Asia,Southeast Asia,1904569,1945,212107000,68,84982,215002,Indonesia,Republic,Abdurrahman Wahid,939,ID\r\nIND,India,Asia,Southern and Central Asia,3287263,1947,1013662000,62.5,447114,430572,Bharat/India,Federal Republic,Kocheril Raman Narayanan,1109,IN\r\nIOT,British Indian Ocean Territory,Africa,Eastern Africa,78,,0,,0,,British Indian Ocean Territory,Dependent Territory of the uK,Elisabeth II,,IO\r\nIRL,Ireland,Europe,British Islands,70273,1921,3775100,76.8,75921,73132,Ireland/eire,Republic,Mary McAleese,1447,IE\r\nIRN,Iran,Asia,Southern and Central Asia,1648195,1906,67702000,69.7,195746,160151,Iran,Islamic Republic,Ali Mohammad Khatami-Ardakani,1380,IR\r\nIRQ,Iraq,Asia,Middle East,438317,1932,23115000,66.5,11500,,Al- Iraq,Republic,Saddam Hussein al-Takriti,1365,IQ\r\nISL,Iceland,Europe,Nordic Countries,103000,1944,279000,79.4,8255,7474,Island,Republic,olafur Ragnar GrImsson,1449,IS\r\nISR,Israel,Asia,Middle East,21056,1948,6217000,78.6,97477,98577,Yisrael/Israil,Republic,Moshe Katzav,1450,IL\r\nITA,Italy,Europe,Southern Europe,301316,1861,57680000,79,1161755,1145372,Italia,Republic,Carlo Azeglio Ciampi,1464,IT\r\nJAM,Jamaica,North America,Caribbean,10990,1962,2583000,75.2,6871,6722,Jamaica,Constitutional Monarchy,Elisabeth II,1530,JM\r\nJOR,Jordan,Asia,Middle East,88946,1946,5083000,77.4,7526,7051,Al-urdunn,Constitutional Monarchy,Abdullah II,1786,JO\r\nJPN,Japan,Asia,Eastern Asia,377829,-660,126714000,80.7,3787042,4192638,Nihon/Nippon,Constitutional Monarchy,Akihito,1532,JP\r\nKAZ,Kazakstan,Asia,Southern and Central Asia,2724900,1991,16223000,63.2,24375,23383,Qazaqstan,Republic,Nursultan Nazarbajev,1864,KZ\r\nKEN,Kenya,Africa,Eastern Africa,580367,1963,30080000,48,9217,10241,Kenya,Republic,Daniel arap Moi,1881,KE\r\nKGZ,Kyrgyzstan,Asia,Southern and Central Asia,199900,1991,4699000,63.4,1626,1767,Kyrgyzstan,Republic,Askar Akajev,2253,KG\r\nKHM,Cambodia,Asia,Southeast Asia,181035,1953,11168000,56.5,5121,5670,Kampuchea,Constitutional Monarchy,Norodom Sihanouk,1800,KH\r\nKIR,Kiribati,Oceania,Micronesia,726,1979,83000,59.8,40.7,,Kiribati,Republic,Teburoro Tito,2256,KI\r\nKNA,Saint Kitts and Nevis,North America,Caribbean,261,1983,38000,70.7,299,,Saint Kitts and Nevis,Constitutional Monarchy,Elisabeth II,3064,KN\r\nKOR,South Korea,Asia,Eastern Asia,99434,1948,46844000,74.4,320749,442544,Taehan Minguk (Namhan),Republic,Kim Dae-jung,2331,KR\r\nKWT,Kuwait,Asia,Middle East,17818,1961,1972000,76.1,27037,30373,Al-Kuwayt,Constitutional Monarchy (Emirate),Jabir al-Ahmad al-Jabir al-Sabah,2429,KW\r\nLAO,Laos,Asia,Southeast Asia,236800,1953,5433000,53.1,1292,1746,Lao,Republic,Khamtay Siphandone,2432,LA\r\nLBN,Lebanon,Asia,Middle East,10400,1941,3282000,71.3,17121,15129,Lubnan,Republic,emile Lahoud,2438,LB\r\nLBR,Liberia,Africa,Western Africa,111369,1847,3154000,51,2012,,Liberia,Republic,Charles Taylor,2440,LR\r\nLBY,Libyan Arab Jamahiriya,Africa,Northern Africa,1759540,1951,5605000,75.5,44806,40562,Libiya,Socialistic State,Muammar al-Qadhafi,2441,LY\r\nLCA,Saint Lucia,North America,Caribbean,622,1979,154000,72.3,571,,Saint Lucia,Constitutional Monarchy,Elisabeth II,3065,LC\r\nLIE,Liechtenstein,Europe,Western Europe,160,1806,32300,78.8,1119,1084,Liechtenstein,Constitutional Monarchy,Hans-Adam II,2446,LI\r\nLKA,Sri Lanka,Asia,Southern and Central Asia,65610,1948,18827000,71.8,15706,15091,Sri Lanka/Ilankai,Republic,Chandrika Kumaratunga,3217,LK\r\nLSO,Lesotho,Africa,Southern Africa,30355,1966,2153000,50.8,1061,1161,Lesotho,Constitutional Monarchy,Letsie III,2437,LS\r\nLTu,Lithuania,Europe,Baltic Countries,65301,1991,3698500,69.1,10692,9585,Lietuva,Republic,Valdas Adamkus,2447,LT\r\nLuX,Luxembourg,Europe,Western Europe,2586,1867,435700,77.1,16321,15519,Luxembourg/Letzebuerg,Constitutional Monarchy,Henri,2452,Lu\r\nLVA,Latvia,Europe,Baltic Countries,64589,1991,2424200,68.4,6398,5639,Latvija,Republic,Vaira Vike-Freiberga,2434,LV\r\nMAC,Macao,Asia,Eastern Asia,18,,473000,81.6,5749,5940,Macau/Aomen,Special Administrative Region of China,Jiang Zemin,2454,MO\r\nMAR,Morocco,Africa,Northern Africa,446550,1956,28351000,69.1,36124,33514,Al-Maghrib,Constitutional Monarchy,Mohammed VI,2486,MA\r\nMCO,Monaco,Europe,Western Europe,1.5,1861,34000,78.8,776,,Monaco,Constitutional Monarchy,Rainier III,2695,MC\r\nMDA,Moldova,Europe,Eastern Europe,33851,1991,4380000,64.5,1579,1872,Moldova,Republic,Vladimir Voronin,2690,MD\r\nMDG,Madagascar,Africa,Eastern Africa,587041,1960,15942000,55,3750,3545,Madagasikara/Madagascar,Federal Republic,Didier Ratsiraka,2455,MG\r\nMDV,Maldives,Asia,Southern and Central Asia,298,1965,286000,62.2,199,,Dhivehi Raajje/Maldives,Republic,Maumoon Abdul Gayoom,2463,MV\r\nMEX,Mexico,North America,Central America,1958201,1810,98881000,71.5,414972,401461,Mexico,Federal Republic,Vicente Fox Quesada,2515,MX\r\nMHL,Marshall Islands,Oceania,Micronesia,181,1990,64000,65.5,97,,Marshall Islands/Majol,Republic,Kessai Note,2507,MH\r\nMKD,Macedonia,Europe,Southern Europe,25713,1991,2024000,73.8,1694,1915,Makedonija,Republic,Boris Trajkovski,2460,MK\r\nMLI,Mali,Africa,Western Africa,1240192,1960,11234000,46.7,2642,2453,Mali,Republic,Alpha Oumar Konare,2482,ML\r\nMLT,Malta,Europe,Southern Europe,316,1964,380200,77.9,3512,3338,Malta,Republic,Guido de Marco,2484,MT\r\nMMR,Myanmar,Asia,Southeast Asia,676578,1948,45611000,54.9,180375,171028,Myanma Pye,Republic,kenraali Than Shwe,2710,MM\r\nMNG,Mongolia,Asia,Eastern Asia,1566500,1921,2662000,67.3,1043,933,Mongol uls,Republic,Natsagiin Bagabandi,2696,MN\r\nMNP,Northern Mariana Islands,Oceania,Micronesia,464,,78000,75.5,0,,Northern Mariana Islands,Commonwealth of the uS,George W. Bush,2913,MP\r\nMOZ,Mozambique,Africa,Eastern Africa,801590,1975,19680000,37.5,2891,2711,Mocambique,Republic,JoaquIm A. Chissano,2698,MZ\r\nMRT,Mauritania,Africa,Western Africa,1025520,1960,2670000,50.8,998,1081,Muritaniya/Mauritanie,Republic,Maaouiya Ould Sid Ahmad Taya,2509,MR\r\nMSR,Montserrat,North America,Caribbean,102,,11000,78,109,,Montserrat,Dependent Territory of the uK,Elisabeth II,2697,MS\r\nMTQ,Martinique,North America,Caribbean,1102,,395000,78.3,2731,2559,Martinique,Overseas Department of France,Jacques Chirac,2508,MQ\r\nMuS,Mauritius,Africa,Eastern Africa,2040,1968,1158000,71,4251,4186,Mauritius,Republic,Cassam uteem,2511,Mu\r\nMWI,Malawi,Africa,Eastern Africa,118484,1964,10925000,37.6,1687,2527,Malawi,Republic,Bakili Muluzi,2462,MW\r\nMYS,Malaysia,Asia,Southeast Asia,329758,1957,22244000,70.8,69213,97884,Malaysia,"Constitutional Monarchy, Federation",Salahuddin Abdul Aziz Shah Alhaj,2464,MY\r\nMYT,Mayotte,Africa,Eastern Africa,373,,149000,59.5,0,,Mayotte,Territorial Collectivity of France,Jacques Chirac,2514,YT\r\nNAM,Namibia,Africa,Southern Africa,824292,1990,1726000,42.5,3101,3384,Namibia,Republic,Sam Nujoma,2726,NA\r\nNCL,New Caledonia,Oceania,Melanesia,18575,,214000,72.8,3563,,Nouvelle-Caledonie,Nonmetropolitan Territory of France,Jacques Chirac,3493,NC\r\nNER,Niger,Africa,Western Africa,1267000,1960,10730000,41.3,1706,1580,Niger,Republic,Mamadou Tandja,2738,NE\r\nNFK,Norfolk Island,Oceania,Australia and New Zealand,36,,2000,,0,,Norfolk Island,Territory of Australia,Elisabeth II,2806,NF\r\nNGA,Nigeria,Africa,Western Africa,923768,1960,111506000,51.6,65707,58623,Nigeria,Federal Republic,Olusegun Obasanjo,2754,NG\r\nNIC,Nicaragua,North America,Central America,130000,1838,5074000,68.7,1988,2023,Nicaragua,Republic,Arnoldo Aleman Lacayo,2734,NI\r\nNIu,Niue,Oceania,Polynesia,260,,2000,,0,,Niue,Nonmetropolitan Territo

In [3]:
#convertir a dataframe
df= pd.read_csv ('CountryTable.csv')
df

,code,name,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,Jose Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the uK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqiperia,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YuG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav KoStunica,1792.0,Yu
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [29]:
#Imprimir primeras 5 filas
df.head(5)

,code,name,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,Jose Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the uK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqiperia,Republic,Rexhep Mejdani,34.0,AL

#Filtro Por Objeto

In [6]:
#Filtro Por objeto 
filtroContinente=df[df['continent']=='South America']
filtroContinente

,code,name,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
8,ARG,Argentina,South America,South America,2780400.0,1816.0,37032000,75.1,340238.0,323310.0,Argentina,Federal Republic,Fernando de la Rua,69.0,AR
29,BOL,Bolivia,South America,South America,1098581.0,1825.0,8329000,63.7,8571.0,7967.0,Bolivia,Republic,Hugo Banzer Suarez,194.0,BO
30,BRA,Brazil,South America,South America,8547403.0,1822.0,170115000,62.9,776739.0,804108.0,Brasil,Federal Republic,Fernando Henrique Cardoso,211.0,BR
40,CHL,Chile,South America,South America,756626.0,1810.0,15211000,75.7,72949.0,75780.0,Chile,Republic,Ricardo Lagos Escobar,554.0,CL
47,COL,Colombia,South America,South America,1138914.0,1810.0,42321000,70.3,102896.0,105116.0,Colombia,Republic,Andres Pastrana Arango,2257.0,CO
62,ECu,Ecuador,South America,South America,283561.0,1822.0,12646000,71.1,19770.0,19769.0,Ecuador,Republic,Gustavo Noboa Bejarano,594.0,EC
71,FLK,Falkland Islands,South America,South America,12173.0,NaN,2000,NaN,0.0,NaN,Falkland Islands,Dependent Territory of the uK,Elisabeth II,763.0,FK
89,GuF,French Guiana,South America,South America,90000.0,NaN,181000,76.1,681.0,NaN,Guyane francaise,Overseas Department of France,Jacques Chirac,3014.0,GF
91,GuY,Guyana,South America,South America,214969.0,1966.0,861000,64.0,722.0,743.0,Guyana,Republic,Bharrat Jagdeo,928.0,GY
167,PER,Peru,South America,South America,1285216.0,1821.0,25662000,70.0,64140.0,65186.0,Peru/Piruw,Republic,Valentin Paniagua Corazao,2890.0,PE
175,PRY,Paraguay,South America,South America,406752.0,1811.0,5496000,73.7,8444.0,9555.0,Paraguay,Republic,Luis angel Gonzalez Macchi,2885.0,PY
197,SuR,Suriname,South America,South America,163265.0,1975.0,417000,71.4,870.0,706.0,Suriname,Republic,Ronald Venetiaan,3243.0,SR
222,uRY,uruguay,South America,South America,175016.0,1828.0,3337000,75.2,20831.0,19967.0,uruguay,Republic,Jorge Batlle Ibanez,3492.0,uY
227,VEN,Venezuela,South America,South America,912050.0,1811.0,24170000,73.1,95023.0,88434.0,Venezuela,Federal Republic,Hugo Chavez FrIas,3539.0,VE

In [7]:
filtroPais=df[df['name']=='Mexico'] 
filtroPais

,code,name,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
135,MEX,Mexico,North America,Central America,1958201.0,1810.0,98881000,71.5,414972.0,401461.0,Mexico,Federal Republic,Vicente Fox Quesada,2515.0,MX

In [9]:
#convertir archivo filtrado a csv
filtroContinente.to_csv("filtroContinente.csv")
filtroPais.to_csv("filtroPais.csv")

In [12]:
#descargar archivo filtrado en csv
from google.colab import files
files.download("filtroContinente.csv")
from google.colab import files
files.download("filtroPais.csv")

# Filtro Por Filas

In [14]:
#FilasConsecutivas
filtroFilasConsecutivas=df.iloc[100:150,:] 
filtroFilasConsecutivas

,code,name,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
100,IOT,British Indian Ocean Territory,Africa,Eastern Africa,78.0,NaN,0,NaN,0.0,NaN,British Indian Ocean Territory,Dependent Territory of the uK,Elisabeth II,NaN,IO
101,IRL,Ireland,Europe,British Islands,70273.0,1921.0,3775100,76.8,75921.0,73132.0,Ireland/eire,Republic,Mary McAleese,1447.0,IE
102,IRN,Iran,Asia,Southern and Central Asia,1648195.0,1906.0,67702000,69.7,195746.0,160151.0,Iran,Islamic Republic,Ali Mohammad Khatami-Ardakani,1380.0,IR
103,IRQ,Iraq,Asia,Middle East,438317.0,1932.0,23115000,66.5,11500.0,NaN,Al- Iraq,Republic,Saddam Hussein al-Takriti,1365.0,IQ
104,ISL,Iceland,Europe,Nordic Countries,103000.0,1944.0,279000,79.4,8255.0,7474.0,Island,Republic,olafur Ragnar GrImsson,1449.0,IS
105,ISR,Israel,Asia,Middle East,21056.0,1948.0,6217000,78.6,97477.0,98577.0,Yisrael/Israil,Republic,Moshe Katzav,1450.0,IL
106,ITA,Italy,Europe,Southern Europe,301316.0,1861.0,57680000,79.0,1161755.0,1145372.0,Italia,Republic,Carlo Azeglio Ciampi,1464.0,IT
107,JAM,Jamaica,North America,Caribbean,10990.0,1962.0,2583000,75.2,6871.0,6722.0,Jamaica,Constitutional Monarchy,Elisabeth II,1530.0,JM
108,JOR,Jordan,Asia,Middle East,88946.0,1946.0,5083000,77.4,7526.0,7051.0,Al-urdunn,Constitutional Monarchy,Abdullah II,1786.0,JO
109,JPN,Japan,Asia,Eastern Asia,377829.0,-660.0,126714000,80.7,3787042.0,4192638.0,Nihon/Nippon,Constitutional Monarchy,Akihito,1532.0,JP
110,KAZ,Kazakstan,Asia,Southern and Central Asia,2724900.0,1991.0,16223000,63.2,24375.0,23383.0,Qazaqstan,Republic,Nursultan Nazarbajev,1864.0,KZ
111,KEN,Kenya,Africa,Eastern Africa,580367.0,1963.0,30080000,48.0,9217.0,10241.0,Kenya,Republic,Daniel arap Moi,1881.0,KE
112,KGZ,Kyrgyzstan,Asia,Southern and Central Asia,199900.0,1991.0,4699000,63.4,1626.0,1767.0,Kyrgyzstan,Republic,Askar Akajev,2253.0,KG
113,KHM,Cambodia,Asia,Southeast Asia,181035.0,1953.0,11168000,56.5,5121.0,5670.0,Kampuchea,Constitutional Monarchy,Norodom Sihanouk,1800.0,KH
114,KIR,Kiribati,Oceania,Micronesia,726.0,1979.0,83000,59.8,40.7,NaN,Kiribati,Republic,Teburoro Tito,2256.0,KI
115,KNA,Saint Kitts and Nevis,North America,Caribbean,261.0,1983.0,38000,70.7,299.0,NaN,Saint Kitts and Nevis,Constitutional Monarchy,Elisabeth II,3064.0,KN
116,KOR,South Korea,Asia,Eastern Asia,99434.0,1948.0,46844000,74.4,320749.0,442544.0,Taehan Minguk (Namhan),Republic,Kim Dae-jung,2331.0,KR
117,KWT,Kuwait,Asia,Middle East,17818.0,1961.0,1972000,76.1,27037.0,30373.0,Al-Kuwayt,Constitutional Monarchy (Emirate),Jabir al-Ahmad al-Jabir al-Sabah,2429.0,KW
118,LAO,Laos,Asia,Southeast Asia,236800.0,1953.0,5433000,53.1,1292.0,1746.0,Lao,Republic,Khamtay Siphandone,2432.0,LA
119,LBN,Lebanon,Asia,Middle East,10400.0,1941.0,3282000,71.3,17121.0,15129.0,Lubnan,Republic,emile Lahoud,2438.0,LB
120,LBR,Liberia,Africa,Western Africa,111369.0,1847.0,3154000,51.0,2012.0,NaN,Liberia,Republic,Charles Taylor,2440.0,LR
121,LBY,Libyan Arab Jamahiriya,Africa,Northern Africa,1759540.0,1951.0,5605000,75.5,44806.0,40562.0,Libiya,Socialistic State,Muammar al-Qadhafi,2441.0,LY
122,LCA,Saint Lucia,North America,Caribbean,622.0,1979.0,154000,72.3,571.0,NaN,Saint Lucia,Constitutional Monarchy,Elisabeth II,3065.0,LC
123,LIE,Liechtenstein,Europe,Western Europe,160.0,1806.0,32300,78.8,1119.0,1084.0,Liechtenstein,Constitutional Monarchy,Hans-Adam II,2446.0,LI
124,LKA,Sri Lanka,Asia,Southern and Central Asia,65610.0,1948.0,18827000,71.8,15706.0,15091.0,Sri Lanka/Ilankai,Republic,Chandrika Kumaratunga,3217.0,LK
125,LSO,Lesotho,Africa,Southern Africa,30355.0,1966.0,2153000,50.8,1061.0,1161.0,Lesotho,Constitutional Monarchy,Letsie III,2437.0,LS
126,LTu,Lithuania,Europe,Baltic Countries,65301.0,1991.0,3698500,69.1,10692.0,9585.0,Lietuva,Republic,Valdas Adamkus,2447.0,LT
127,LuX,Luxembourg,Europe,Western Europe,2586.0,1867.0,435700,77.1,16321.0,15519.0,Luxembourg/Letzebuerg,Constitutional Monarchy,Henri,2452.0,Lu
128,LVA,Latvia,Europe,Baltic Countries,64589.0,1991.0,2424200,68.4,6398.0,5639.0,Latvija,Republic,Vaira Vike-Freiberga,2434.0,LV
129,MAC,Macao,Asia,Eastern Asia,18.0,NaN,473000,81.6,5749.0,5940.0,Macau/Aomen,Special Administrative Region of China,Jiang Zemin,2454.0,MO
130,MAR,Morocco,Africa,Northern Africa,446550.0,1956.0,28351000,69.1,36124.0,33514.0,Al-Maghrib,Constitutional Monarchy,Mohammed VI,2486.0,MA
131,MCO,Monaco,Europe,Western Europe,1.5,1861.0,34000,78.8,776.0,NaN,Monaco,Constitutional Monarchy,Rainier III,2695.0,MC
132,MDA,Moldova,Europe,Eastern Europe,33851.0,1991.0,4380000,64.5,1579.0,1872.0,Moldova,Republic,Vladimir Voronin,2690.0,MD
133,MDG,Madagascar,Africa,Eastern Africa,587041.0,1960.0,15942000,55.0,3750.0,3545.0,Madagasikara/Madagascar,Federal Republic,Didier Ratsiraka,2455.0,MG
134,MDV,Maldives,Asia,Southern and Central Asia,298.0,1965.0,286000,62.2,199.0,NaN,Dhivehi Raajje/Maldives,Republic,Maumoon Abdul Gayoom,2463.0,MV
135,MEX,Mexico,North America,Central America,1958201.0,1810.0,98881000,71.5,414972.0,401461.0,Mexico,Federal Republic,Vicente Fox Quesada,2515.0,MX
136,MHL,Marshall Islands,Oceania,Micronesia,181.0,1990.0,64000,65.5,97.0,NaN,Marshall Islands/Majol,Republic,Kessai Note,2507.0,MH
137,MKD,Macedonia,Europe,Southern Europe,25713.0,1991.0,2024000,73.8,1694.0,1915.0,Makedonija,Republic,Boris Trajkovski,2460.0,MK
138,MLI,Mali,Africa,Western Africa,1240192.0,1960.0,11234000,46.7,2642.0,2453.0,Mali,Republic,Alpha Oumar Konare,2482.0,ML
139,MLT,Malta,Europe,Southern Europe,316.0,1964.0,380200,77.9,3512.0,3338.0,Malta,Republic,Guido de Marco,2484.0,MT
140,MMR,Myanmar,Asia,Southeast Asia,676578.0,1948.0,45611000,54.9,180375.0,171028.0,Myanma Pye,Republic,kenraali Than Shwe,2710.0,MM
141,MNG,Mongolia,Asia,Eastern Asia,1566500.0,1921.0,2662000,67.3,1043.0,933.0,Mongol uls,Republic,Natsagiin Bagabandi,2696.0,MN
142,MNP,Northern Mariana Islands,Oceania,Micronesia,464.0,NaN,78000,75.5,0.0,NaN,Northern Mariana Islands,Commonwealth of the uS,George W. Bush,2913.0,MP
143,MOZ,Mozambique,Africa,Eastern Africa,801590.0,1975.0,19680000,37.5,2891.0,2711.0,Mocambique,Republic,JoaquIm A. Chissano,2698.0,MZ
144,MRT,Mauritania,Africa,Western Africa,1025520.0,1960.0,2670000,50.8,998.0,1081.0,Muritaniya/Mauritanie,Republic,Maaouiya Ould Sid Ahmad Taya,2509.0,MR
145,MSR,Montserrat,North America,Caribbean,102.0,NaN,11000,78.0,109.0,NaN,Montserrat,Dependent Territory of the uK,Elisabeth II,2697.0,MS
146,MTQ,Martinique,North America,Caribbean,1102.0,NaN,395000,78.3,2731.0,2559.0,Martinique,Overseas Department of France,Jacques Chirac,2508.0,MQ
147,MuS,Mauritius,Africa,Eastern Africa,2040.0,1968.0,1158000,71.0,4251.0,4186.0,Mauritius,Republic,Cassam uteem,2511.0,Mu
148,MWI,Malawi,Africa,Eastern Africa,118484.0,1964.0,10925000,37.6,1687.0,2527.0,Malawi,Republic,Bakili Muluzi,2462.0,MW
149,MYS,Malaysia,Asia,Southeast Asia,329758.0,1957.0,22244000,70.8,69213.0,97884.0,Malaysia,"Constitutional Monarchy, Federation",Salahuddin Abdul Aziz Shah Alhaj,2464.0,MY

In [18]:
#Filas no Consecutivas
filtroFilasNoConsecutivas=df.iloc[[1,10,100,122,150,148,27,18],:]
filtroFilasNoConsecutivas

,code,name,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
10,ASM,American Samoa,Oceania,Polynesia,199.0,NaN,68000,75.1,334.0,NaN,Amerika Samoa,uS Territory,George W. Bush,54.0,AS
100,IOT,British Indian Ocean Territory,Africa,Eastern Africa,78.0,NaN,0,NaN,0.0,NaN,British Indian Ocean Territory,Dependent Territory of the uK,Elisabeth II,NaN,IO
122,LCA,Saint Lucia,North America,Caribbean,622.0,1979.0,154000,72.3,571.0,NaN,Saint Lucia,Constitutional Monarchy,Elisabeth II,3065.0,LC
150,MYT,Mayotte,Africa,Eastern Africa,373.0,NaN,149000,59.5,0.0,NaN,Mayotte,Territorial Collectivity of France,Jacques Chirac,2514.0,YT
148,MWI,Malawi,Africa,Eastern Africa,118484.0,1964.0,10925000,37.6,1687.0,2527.0,Malawi,Republic,Bakili Muluzi,2462.0,MW
27,BLZ,Belize,North America,Central America,22696.0,1981.0,241000,70.9,630.0,616.0,Belize,Constitutional Monarchy,Elisabeth II,185.0,BZ
18,BEL,Belgium,Europe,Western Europe,30518.0,1830.0,10239000,77.8,249704.0,243948.0,Belgie/Belgique,"Constitutional Monarchy, Federation",Albert II,179.0,BE

In [21]:
#convertir archivo filtrado a csv
filtroFilasConsecutivas.to_csv("filtroFilasConsecutivas.csv")
filtroFilasNoConsecutivas.to_csv("filtroFilasNoConsecutivas.csv")

In [22]:
#descargar archivo filtrado en csv
from google.colab import files
files.download("filtroFilasConsecutivas.csv")
from google.colab import files
files.download("filtroFilasNoConsecutivas.csv")

# Filtro Por Columna

In [23]:
#columnas consecutivas
filtroColumnasConsecutivas=df.iloc[:, 5:10]
filtroColumnasConsecutivas

     independence_year  population  life_expectancy       gnp   gnp_old
0                  NaN      103000             78.4     828.0     793.0
1               1919.0    22720000             45.9    5976.0       NaN
2               1975.0    12878000             38.3    6648.0    7984.0
3                  NaN        8000             76.1      63.2       NaN
4               1912.0     3401200             71.6    3205.0    2500.0
..                 ...         ...              ...       ...       ...
234             1918.0    18112000             59.8    6041.0    5729.0
235             1918.0    10640000             72.4   17000.0       NaN
236             1910.0    40377000             51.1  116729.0  129092.0
237             1964.0     9169000             37.2    3377.0    3922.0
238             1980.0    11669000             37.8    5951.0    8670.0

[239 rows x 5 columns]

In [25]:
#FiltroColumnasNoConsecutivas
filtroColumnasNoConsecutivas=df.iloc[:,[2,4,6,8,10]]
filtroColumnasNoConsecutivas

         continent  surface_area  population       gnp             local_name
0    North America         193.0      103000     828.0                  Aruba
1             Asia      652090.0    22720000    5976.0  Afganistan/Afqanestan
2           Africa     1246700.0    12878000    6648.0                 Angola
3    North America          96.0        8000      63.2               Anguilla
4           Europe       28748.0     3401200    3205.0              Shqiperia
..             ...           ...         ...       ...                    ...
234           Asia      527968.0    18112000    6041.0               Al-Yaman
235         Europe      102173.0    10640000   17000.0            Jugoslavija
236         Africa     1221037.0    40377000  116729.0           South Africa
237         Africa      752618.0     9169000    3377.0                 Zambia
238         Africa      390757.0    11669000    5951.0               Zimbabwe

[239 rows x 5 columns]

In [26]:
#convertir archivo filtrado a csv
filtroColumnasConsecutivas.to_csv("filtroColumnasConsecutivas.csv")
filtroColumnasNoConsecutivas.to_csv("filtroColumasNoConsecutivas.csv")

In [28]:
#descargar archivo filtrado en csv
from google.colab import files
files.download("filtroColumnasConsecutivas.csv")
from google.colab import files
files.download("filtroColumasNoConsecutivas.csv")

# Filtro Por Columnas y Filas